### ISSUE TITLE
[Lobby] - Save user

### ISSUE THREAD

**Issue by cezarywojcik** [RatDevelopment/WebCiv#12]
Save the mongo _id attribute of the user to localStorage clientside. Look into potential uses for this. Problem: If we use this local value to make the site remember the user, then we can't delete the user from mongo on socket disconnect. If this is the case, when would we remove that user?

**Comment by Serneum** [comment]
Couldn't socket disconnect also remove the id from localStorage?

**Comment by cezarywojcik** [comment]
No, it can't. Socket disconnect can be called if, say, user closes the browser. There's nothing more you can do clientside. That said, even if we could do it, it wouldn't be useful because the point of saving the _id in localstorage is to save the user even if the user closes the page and browser.

**Comment by cezarywojcik** [comment]
Saving user **name** added; no _id usage yet.

https://github.com/RatDevelopment/WebCiv/commit/f6bf92251e940771cb6f7eb3bf2262ab0c94eb9a
