### ISSUE TITLE
Look into MongoDB in the context of Angular.js and Node.js

### ISSUE THREAD

**Issue by cezarywojcik** [RatDevelopment/WebCiv#3]
Using http://mongoosejs.com/ might be a good option.

**Comment by Serneum** [comment]
Possible plugins:
https://github.com/rithis/cruder
https://github.com/enyo/mongo-rest
https://github.com/banchee/tranquil
https://github.com/oct8cat/remo
https://github.com/wearefractal/seedling
https://github.com/Unitech/angular-bridge
https://github.com/IlskenLabs/mongoose-construct
