### ISSUE TITLE
Specify a flat coordinates to isometric coordinates function

### ISSUE THREAD

**Issue by cezarywojcik** [RatDevelopment/WebCiv#5]

**Comment by Serneum** [comment]
x, y, z should really be all we need. We just need to layer objects, so basically start with furthest back and keep drawing things closer to the camera

**Comment by cezarywojcik** [comment]
In the isogrid branch (https://github.com/RatDevelopment/WebCiv/tree/isogrid), I added an isotest.html that we can use to test the `toIso` function (https://github.com/RatDevelopment/WebCiv/blob/isogrid/res/js/isogrid.js#L10).

We can mess with the `toIso` function (we also need to mess with the camera object - https://github.com/RatDevelopment/WebCiv/blob/isogrid/res/js/isogrid.js#L21) to start implementing isometric stuff.

**Comment by cezarywojcik** [comment]
A useful page:

http://www.gamedev.net/page/resources/_/technical/game-programming/isometric-n-hexagonal-maps-part-i-r747

**Comment by cezarywojcik** [comment]
I attempted to make a rotated and vertically diluted hex grid, but that did not work out very well.

Square grid with this method:
![r4ui5en](https://f.cloud.github.com/assets/4251446/657671/1fdf0466-d56e-11e2-85f0-1e1d233765ea.png)

Hex grid with this method:
![mtheifr](https://f.cloud.github.com/assets/4251446/657672/24526dee-d56e-11e2-9f89-0421b1ed5793.png)

The hex doesn't quite look good enough, so I'm currently experimenting with 3D. Though I think 3D is the incorrect thing to do here, because all tiles should be uniform.

**Comment by cezarywojcik** [comment]
We will be using hexes 128x106px.
