### ISSUE TITLE
Get sample images to test isometric grid

### ISSUE THREAD

**Issue by cezarywojcik** [RatDevelopment/WebCiv#6]
We'll need at least 3 different tile types and corresponding borders.

Width: 128px
Height: 106px

Hex edge heights (from bottom): 80px, 27px (26px, 79px from top)

**Comment by forRuin** [comment]
![hexdemo](https://f.cloud.github.com/assets/2482957/661011/17ad0e56-d725-11e2-808b-d3f581866d20.png)

Here's an example of what I was talking about (obviously without edge tiling) for putting 6 tiles into one hex.  If we're really short on space we could probably fit 12.

**Comment by cezarywojcik** [comment]
My only concern would be whether this sort of tiling can look too obvious and not as organic as we'd like, but I can't really tell without samples.

**Comment by cezarywojcik** [comment]
I made a few sample images for now.
